(function(){
'use strict';
var selected='', cache={access:[],timings:[]};
function cfg(){return window.configElezioni||{}}
function pol(){return window.LeviElectionPolicy}
function api(){return window.SECURE_API}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function notify(t,m,k){if(window.showNotification)window.showNotification(t,m,k||'info')}
function enabled(){try{return pol().enabled(cfg())}catch(e){return[]}}
function label(k){try{return pol().ELECTIONS[k].label}catch(e){return k}}
function choose(){var a=enabled();if(!selected||a.indexOf(selected)<0)selected=a[0]||'';return a}
function options(){return choose().map(function(k){return '<option value="'+esc(k)+'" '+(k===selected?'selected':'')+'>'+esc(label(k))+'</option>'}).join('')}
function lastClose(k){try{var p=pol().profile(cfg(),k),w=(p.windows||[]).filter(function(x){return x&&x.date&&x.to}).slice().sort(function(a,b){return (a.date+'T'+a.to).localeCompare(b.date+'T'+b.to)});var x=w[w.length-1]||{};return {date:x.date||'',time:x.to||''}}catch(e){return{date:'',time:''}}}
function typeLabel(v){return {DOCUMENTALE_241:'Accesso documentale - L. 241/1990',CIVICO_SEMPLICE:'Accesso civico semplice - art. 5, c. 1, D.Lgs. 33/2013',CIVICO_GENERALIZZATO:'Accesso civico generalizzato - art. 5, c. 2, D.Lgs. 33/2013'}[v]||v}
function outcomeLabel(v){return {IN_ISTRUTTORIA:'In istruttoria',VISIONE:'Visione',COPIA:'Rilascio copia',ACCOGLIMENTO_PARZIALE:'Accoglimento parziale',DIFFERIMENTO:'Differimento',DINIEGO:'Diniego'}[v]||v}

window.selectAccessElection=function(k){selected=k;window.renderAccessoAttiTab(document.getElementById('admin-tab-content'))};

window.renderAccessoAttiTab=async function(container){
 if(!container)return;
 if(!choose().length){container.innerHTML='<div class="bg-white rounded-3xl border p-6 font-bold">Nessuna consultazione attiva configurata.</div>';return}
 container.innerHTML='<div class="bg-white rounded-3xl border p-6 font-bold">Caricamento registro...</div>';
 try{var r=await api().getAccessProcedureState({annoScolastico:cfg().annoScolastico,electionKey:selected});cache=r.data||{access:[],timings:[]}}catch(e){cache={access:[],timings:[]}}
 var close=lastClose(selected);
 var ar=(cache.access||[]).map(function(x){return '<tr class="border-t"><td class="p-2">'+esc(x.requestProtocol)+'<br><small>'+esc(x.requestDate)+'</small></td><td class="p-2">'+esc(typeLabel(x.requestType))+'</td><td class="p-2">'+esc(x.requesterQualification)+'</td><td class="p-2">'+esc(outcomeLabel(x.outcome))+'</td><td class="p-2">'+esc(x.responseProtocol||'-')+'</td><td class="p-2"><button onclick="window.downloadAccessRecordPDF(\''+esc(x.id)+'\')" class="px-2 py-1 bg-slate-900 text-white rounded-lg font-black">PDF</button></td></tr>'}).join('');
 var tr=(cache.timings||[]).map(function(x){return '<tr class="border-t"><td class="p-2">'+esc(x.scrutinyDate)+'</td><td class="p-2">'+esc(x.scheduledCloseTime||'-')+'</td><td class="p-2">'+esc(x.actualStartTime)+'</td><td class="p-2">'+esc(x.actualEndTime)+'</td><td class="p-2">'+(x.interrupted?'SI':'NO')+'</td><td class="p-2">'+esc(x.protocolRef)+'</td><td class="p-2"><button onclick="window.downloadScrutinyTimingPDF(\''+esc(x.id)+'\')" class="px-2 py-1 bg-slate-900 text-white rounded-lg font-black">PDF</button></td></tr>'}).join('');
 var h=[];
 h.push('<div class="w-full space-y-5 font-semibold">');
 h.push('<div class="bg-white rounded-3xl shadow border p-6"><div class="flex flex-col md:flex-row justify-between gap-4"><div><span class="text-[9px] bg-blue-900 text-white px-2 py-1 rounded font-black">AREA RISERVATA COMMISSIONE</span><h3 class="text-xl font-black mt-2">Accesso agli atti e tempi dello scrutinio</h3><p class="text-[10px] text-slate-500">Registro amministrativo di supporto. Non pubblica risultati analitici e non sostituisce protocollo, provvedimenti dell Istituto o verbali ufficiali.</p></div><label class="text-xs min-w-[280px]">Consultazione attiva<select onchange="window.selectAccessElection(this.value)" class="mt-1 w-full p-3 border rounded-xl text-black">'+options()+'</select></label></div>');
 h.push('<div class="mt-4 grid md:grid-cols-2 gap-3 text-[10px]"><div class="rounded-2xl border bg-slate-50 p-4"><b>Accesso documentale</b><br>L. 241/1990, artt. 22, 24 e 25; D.P.R. 184/2006, art. 6. La richiesta documentale deve essere motivata e riferita a un interesse diretto, concreto e attuale; il procedimento formale si conclude di regola entro trenta giorni.</div><div class="rounded-2xl border bg-slate-50 p-4"><b>Accesso civico</b><br>D.Lgs. 33/2013, artt. 5 e 5-bis. L accesso semplice riguarda pubblicazioni obbligatorie omesse; il generalizzato riguarda ulteriori dati e documenti nei limiti di legge, compresa la protezione dei dati personali.</div><div class="rounded-2xl border bg-blue-50 p-4"><b>O.M. 215/1991, art. 46, comma 3</b><br>Per verbali e atti degli scrutini è previsto uno specifico diritto di accesso per i soggetti indicati dalla norma: componenti della Commissione in sede di esame dei ricorsi, rappresentanti di lista e candidati.</div><div class="rounded-2xl border bg-blue-50 p-4"><b>O.M. 215/1991, artt. 45-46</b><br>La comunicazione pubblica riguarda l elenco degli eletti proclamati. Il dettaglio degli scrutini resta negli atti e non viene automaticamente pubblicato nel portale.</div></div></div>');
 h.push('<div class="grid xl:grid-cols-2 gap-5">');
 h.push('<form onsubmit="event.preventDefault();window.recordDocumentAccessFromForm(this)" class="bg-white rounded-3xl shadow border p-5 space-y-3"><b>Registro richiesta di accesso agli atti</b><p class="text-[10px] text-slate-500">Non inserire token elettorali o dati idonei a collegare il singolo elettore al voto.</p><label class="block text-xs">Tipo<select name="requestType" class="w-full p-2 border rounded-xl"><option value="DOCUMENTALE_241">Documentale - L. 241/1990</option><option value="CIVICO_SEMPLICE">Civico semplice - D.Lgs. 33/2013</option><option value="CIVICO_GENERALIZZATO">Civico generalizzato - D.Lgs. 33/2013</option></select></label><div class="grid md:grid-cols-2 gap-2"><label class="text-xs">Protocollo richiesta<input required name="requestProtocol" class="w-full p-2 border rounded-xl"></label><label class="text-xs">Data richiesta<input required type="date" name="requestDate" class="w-full p-2 border rounded-xl"></label></div><label class="block text-xs">Qualifica/interesse dichiarato<input required name="requesterQualification" maxlength="200" class="w-full p-2 border rounded-xl"></label><label class="block text-xs">Atti richiesti<textarea required name="documents" maxlength="2000" class="w-full p-2 border rounded-xl"></textarea></label><label class="block text-xs">Esito<select name="outcome" class="w-full p-2 border rounded-xl"><option value="IN_ISTRUTTORIA">In istruttoria</option><option value="VISIONE">Visione</option><option value="COPIA">Rilascio copia</option><option value="ACCOGLIMENTO_PARZIALE">Accoglimento parziale</option><option value="DIFFERIMENTO">Differimento</option><option value="DINIEGO">Diniego</option></select></label><div class="grid md:grid-cols-2 gap-2"><label class="text-xs">Protocollo risposta<input name="responseProtocol" class="w-full p-2 border rounded-xl"></label><label class="text-xs">Data risposta<input type="date" name="responseDate" class="w-full p-2 border rounded-xl"></label></div><label class="block text-xs">Omissis / limitazioni<textarea name="redactions" maxlength="1500" class="w-full p-2 border rounded-xl"></textarea></label><label class="block text-xs">Annotazioni<textarea name="notes" maxlength="2000" class="w-full p-2 border rounded-xl"></textarea></label><button class="w-full p-3 bg-blue-900 text-white rounded-xl text-xs font-black">REGISTRA PRATICA</button></form>');
 h.push('<form onsubmit="event.preventDefault();window.recordScrutinyTimingFromForm(this)" class="bg-white rounded-3xl shadow border p-5 space-y-3"><b>Verbale tempi dello scrutinio</b><p class="text-[10px] text-slate-500">O.M. 215/1991, art. 43, comma 1: lo scrutinio inizia immediatamente dopo la chiusura e non può essere interrotto fino al completamento.</p><div class="grid md:grid-cols-2 gap-2"><label class="text-xs">Data scrutinio<input required type="date" name="scrutinyDate" value="'+esc(close.date)+'" class="w-full p-2 border rounded-xl"></label><label class="text-xs">Chiusura prevista<input type="time" name="scheduledCloseTime" value="'+esc(close.time)+'" class="w-full p-2 border rounded-xl"></label></div><div class="grid md:grid-cols-2 gap-2"><label class="text-xs">Inizio effettivo<input required type="time" name="actualStartTime" class="w-full p-2 border rounded-xl"></label><label class="text-xs">Fine effettiva<input required type="time" name="actualEndTime" class="w-full p-2 border rounded-xl"></label></div><label class="flex gap-2 text-xs"><input type="checkbox" name="interrupted"> Operazioni interrotte</label><label class="block text-xs">Motivazione interruzione<textarea name="interruptionReason" maxlength="1500" class="w-full p-2 border rounded-xl"></textarea></label><label class="block text-xs">Verbale/protocollo di riferimento<input required name="protocolRef" maxlength="200" class="w-full p-2 border rounded-xl"></label><label class="block text-xs">Annotazioni<textarea name="notes" maxlength="1500" class="w-full p-2 border rounded-xl"></textarea></label><button class="w-full p-3 bg-slate-900 text-white rounded-xl text-xs font-black">REGISTRA ORARI SCRUTINIO</button><div class="rounded-xl bg-amber-50 border border-amber-200 p-3 text-[10px]"><b>Nota:</b> il sistema conserva gli orari reali e non applica tolleranze arbitrarie. Eventuali ritardi o interruzioni devono essere motivati nel verbale.</div></form></div>');
 h.push('<div class="bg-white rounded-3xl shadow border p-5"><b>Pratiche di accesso registrate</b><div class="overflow-auto mt-3 border rounded-xl"><table class="w-full text-[10px]"><thead><tr class="bg-slate-50"><th class="p-2">Richiesta</th><th class="p-2">Tipo</th><th class="p-2">Qualifica</th><th class="p-2">Esito</th><th class="p-2">Risposta</th><th class="p-2">PDF</th></tr></thead><tbody>'+(ar||'<tr><td colspan="6" class="p-5 text-center">Nessuna pratica registrata.</td></tr>')+'</tbody></table></div></div>');
 h.push('<div class="bg-white rounded-3xl shadow border p-5"><b>Orari dello scrutinio registrati</b><div class="overflow-auto mt-3 border rounded-xl"><table class="w-full text-[10px]"><thead><tr class="bg-slate-50"><th class="p-2">Data</th><th class="p-2">Chiusura</th><th class="p-2">Inizio</th><th class="p-2">Fine</th><th class="p-2">Interruzione</th><th class="p-2">Verbale</th><th class="p-2">PDF</th></tr></thead><tbody>'+(tr||'<tr><td colspan="7" class="p-5 text-center">Nessun orario registrato.</td></tr>')+'</tbody></table></div></div>');
 h.push('<div class="bg-white rounded-3xl shadow border p-5 text-[10px]"><b>Riferimenti</b><br>O.M. 15 luglio 1991 n. 215, artt. 43, 45 e 46; L. 7 agosto 1990 n. 241, artt. 22, 24 e 25; D.P.R. 12 aprile 2006 n. 184, art. 6; D.Lgs. 14 marzo 2013 n. 33, artt. 5 e 5-bis; Regolamento (UE) 2016/679.</div></div>');
 container.innerHTML=h.join('');
 if(window.lucide)window.lucide.createIcons();
};

window.recordDocumentAccessFromForm=async function(form){
 var d=new FormData(form);
 try{var r=await api().recordDocumentAccess({annoScolastico:cfg().annoScolastico,electionKey:selected,requestType:d.get('requestType'),requestProtocol:d.get('requestProtocol').trim(),requestDate:d.get('requestDate'),requesterQualification:d.get('requesterQualification').trim(),documents:d.get('documents').trim(),outcome:d.get('outcome'),responseProtocol:d.get('responseProtocol').trim(),responseDate:d.get('responseDate'),redactions:d.get('redactions').trim(),notes:d.get('notes').trim()});notify('Pratica registrata','Registro aggiornato. ID: '+(r.data&&r.data.id||'registrato'),'success');window.renderAccessoAttiTab(document.getElementById('admin-tab-content'))}catch(e){notify('Registrazione non riuscita',e.message||'Errore','error')}
};
window.recordScrutinyTimingFromForm=async function(form){
 var d=new FormData(form);
 try{var r=await api().recordScrutinyTiming({annoScolastico:cfg().annoScolastico,electionKey:selected,scrutinyDate:d.get('scrutinyDate'),scheduledCloseTime:d.get('scheduledCloseTime'),actualStartTime:d.get('actualStartTime'),actualEndTime:d.get('actualEndTime'),interrupted:d.has('interrupted'),interruptionReason:d.get('interruptionReason').trim(),protocolRef:d.get('protocolRef').trim(),notes:d.get('notes').trim()});notify('Orari registrati','Tempi dello scrutinio acquisiti. ID: '+(r.data&&r.data.id||'registrato'),'success');window.renderAccessoAttiTab(document.getElementById('admin-tab-content'))}catch(e){notify('Registrazione non riuscita',e.message||'Errore','error')}
};
function pdfHeader(doc,title){doc.setFillColor(30,58,138);doc.rect(0,0,210,34,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text('ITSCG PRIMO LEVI DI SEREGNO',15,13);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(title,15,22);doc.setTextColor(30,41,59)}
function writer(doc){var y=44;return function(t,v){doc.setFont('helvetica','bold');doc.text(t,15,y);doc.setFont('helvetica','normal');var z=doc.splitTextToSize(String(v||'-'),175);doc.text(z,15,y+5);y+=10+z.length*4;if(y>260){doc.addPage();y=22}return y}}
window.downloadAccessRecordPDF=function(id){
 var x=(cache.access||[]).find(function(a){return a.id===id});if(!x)return notify('Verbale non disponibile','Ricaricare la pagina','error');
 var J=window.jspdf.jsPDF,doc=new J(),w=writer(doc);pdfHeader(doc,'Registro / verbale amministrativo di accesso agli atti elettorali');
 w('Anno scolastico',cfg().annoScolastico);w('Consultazione',label(x.electionKey));w('Richiesta',(x.requestProtocol||'-')+' - '+(x.requestDate||'-'));w('Tipologia',typeLabel(x.requestType));w('Qualifica/interesse dichiarato',x.requesterQualification);w('Atti richiesti',x.documents);w('Esito',outcomeLabel(x.outcome));w('Risposta',(x.responseProtocol||'-')+' - '+(x.responseDate||'-'));w('Omissis / limitazioni',x.redactions||'Nessuna annotazione');w('Annotazioni',x.notes||'Nessuna');w('Norme','O.M. 215/1991 art. 46, c. 3; L. 241/1990 artt. 22, 24, 25; D.P.R. 184/2006 art. 6; D.Lgs. 33/2013 artt. 5 e 5-bis; Reg. UE 2016/679.');w('Estratti essenziali','O.M. 215/1991 art. 45, c. 2: Degli eletti proclamati va data comunicazione mediante affissione del relativo elenco nell albo della scuola. L. 241/1990 art. 25, c. 2: La richiesta di accesso ai documenti deve essere motivata. D.P.R. 184/2006 art. 6, c. 4: Il procedimento di accesso deve concludersi nel termine di trenta giorni.');w('Avvertenza','Questo documento registra la gestione amministrativa. Il provvedimento di accoglimento, diniego, limitazione o differimento resta atto dell Istituzione scolastica competente.');w('Sottoscrizione','Commissione/responsabile competente: ____________________   Firma: ____________________');doc.save('Verbale_Accesso_Atti_'+x.electionKey+'.pdf')
};
window.downloadScrutinyTimingPDF=function(id){
 var x=(cache.timings||[]).find(function(a){return a.id===id});if(!x)return notify('Verbale non disponibile','Ricaricare la pagina','error');
 var J=window.jspdf.jsPDF,doc=new J(),w=writer(doc);pdfHeader(doc,'Verbale di rilevazione dei tempi dello scrutinio');
 w('Anno scolastico',cfg().annoScolastico);w('Consultazione',label(x.electionKey));w('Data scrutinio',x.scrutinyDate);w('Ora chiusura prevista',x.scheduledCloseTime||'Non indicata');w('Ora effettiva di inizio',x.actualStartTime);w('Ora effettiva di fine',x.actualEndTime);w('Interruzione',x.interrupted?'SI':'NO');if(x.interrupted)w('Motivazione interruzione',x.interruptionReason||'Da integrare');w('Verbale/protocollo',x.protocolRef);w('Annotazioni',x.notes||'Nessuna');w('O.M. 215/1991, art. 43, comma 1','Le operazioni di scrutinio hanno inizio immediatamente dopo la chiusura delle votazioni e non possono essere interrotte fino al loro completamento.');w('Nota','Il sistema non introduce tolleranze o deroghe. Ritardi o interruzioni devono risultare motivati nel verbale.');w('Sottoscrizione','Presidente/Commissione: ____________________   Firma: ____________________');doc.save('Verbale_Tempi_Scrutinio_'+x.electionKey+'_'+x.scrutinyDate+'.pdf')
};
})();