(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.LeviDpoDossier=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const VERSION='LEVI_DPO_REVIEW_2026_V1';
 const fields={legalBasis:'Atti e base giuridica della specifica consultazione',dpoOpinion:'Parere DPO e screening / valutazione di impatto',providers:'Fornitori, localizzazioni, contratti e trasferimenti',backups:'Backup: contenuti, frequenza, ubicazione, cifratura, accessi e ripristino',retention:'Conservazione, cancellazione, esportazioni e legal hold',riskAssessment:'Analisi dei rischi e misure residue',incidentResponse:'Incidenti e data breach: ruoli, recapiti e tempi',stationProcedure:'Riconoscimento in presenza, codici casuali e postazione assistita',evidenceCustody:'Custodia delle evidenze, chiavi, firma e protocollo',accessibility:'Accessibilità e alternative ammesse'};
 const sections=[
 {title:'1. Finalità e ruolo del DPO',paragraphs:[
 'Destinatario: Vargiu Scuola S.r.l., dpo@vargiuscuola.it, come indicato nell’Allegato A e confermato dal referente della scuola. Il fascicolo supporta la valutazione privacy di una versione e configurazione individuate; non è un certificato di conformità.',
 'Al DPO non è chiesto di certificare la validità giuridica delle elezioni o di autorizzare il voto telematico. Gli è chiesto di valutare i trattamenti, i rischi e le misure di protezione dei dati, nell’ambito delle proprie competenze. Il Titolare conserva la responsabilità delle decisioni. Gli organi competenti adottano gli atti elettorali.',
 'Lo screening sulla necessità della DPIA deve essere documentato. Se il trattamento può presentare un rischio elevato, la DPIA precede l’avvio; un rischio elevato residuo richiede la valutazione della consultazione preventiva prevista dall’art. 36. Questo fascicolo non equivale a una DPIA approvata.'
 ]},
 {title:'2. Database: architettura logica e separazione',paragraphs:[
 'Firestore: radice artifacts/iis-levi-electoral-v3/public/data. Le raccolte annuali terminano in _YYYY_YYYY; config contiene yearly_settings_YYYY_YYYY. Non esistono join SQL: le relazioni applicative usano anno, componente, classe e identificativi casuali. L’API legge la configurazione annuale e controlla ruolo, account attivo, versione della sessione e ambito temporale.',
 'Nella modalità PRESENTIAL_UNLINKED_V1 il registro nominativo è usato per gli aventi diritto e l’eleggibilità, ma non viene aggiornato al deposito del voto. Il riconoscimento e la consegna sono registrati dal seggio separatamente, senza codice o orario puntuale abbinato al nome. Codici mescolati e cedolini chiusi non devono essere distribuiti nell’ordine degli elenchi. Non inviarli con email nominative. Il processo è diverso dal vecchio token associato a una persona.'
 ],rows:[
 ['Raccolta','Chiavi / dati','Accesso e relazione'],
 ['tokens_anno','ID della credenziale storica; nome, componente, classe, indirizzo; eventuali vecchi flag','Registro nominativo: Commissione. Nel nuovo processo non autentica il voto e non riceve flag di partecipazione. Nessuna migrazione che colleghi i nuovi codici ai nomi.'],
 ['credenziali_anonime_anno','SHA-256(anno:codice casuale da 128 bit); componente, classe, flag; hash sessione e ricevuta tecnica','Solo API Admin SDK; nessun nome, email, ID del registro o ID di scheda. Un hash casuale è ancora un identificatore, non prova di anonimato assoluto.'],
 ['lotti_credenziali_anno','Hash componente/classe; quantità emessa e aventi diritto','Conteggi del lotto. Limite agli aventi diritto del gruppo. Nessun elenco di abbinamenti o codice in chiaro.'],
 ['voti_consiglio / istituto / consulta / classe_studenti / classe_genitori_anno','ID UUID casuale; schema, keyId, IV, tag e ciphertext a dimensione fissa','Urne distinte; nessun token, nome dell’elettore, sessione o timestamp applicativo. Il database conserva comunque metadati nativi.'],
 ['gestione_accessi_anno','ID account; ruolo, nome operatore, username, salt/hash password, active, sessionVersion, scadenza','API staff. Il personale usa Firebase Auth con token personalizzato; gli elettori non usano un’identità Firebase nella modalità nuova.'],
 ['regolarita / eventi_procedimento / audit_tecnico_anno','Controlli, proposta, verifica, autorizzazione, sospensione/ripresa, esiti, riferimenti','Storia delle operazioni di staff, senza contenuti dei voti. Fascicolo privacy e rapporti riservati.'],
 ['config e audit_admin','Calendario, liste pubbliche, atti; audit operazioni gestionali','La configurazione è pubblica: mai inserirvi segreti o informative riservate. Le scritture passano dalle API.']
 ]},
 {title:'3. Flusso del voto, unicità e recupero',paragraphs:[
 'La Commissione definisce gli elenchi; genera i lotti prima dell’autorizzazione. Il programma crea i codici indipendentemente dai nominativi e ne restituisce il testo una sola volta, per la stampa custodita. Il seggio identifica l’avente diritto, registra la consegna secondo la procedura adottata e gli fa estrarre un cedolino chiuso dal lotto della componente/classe. La postazione non deve registrare lo schermo o la sequenza nominativa degli accessi.',
 'Il codice apre una sessione casuale valida al massimo 15 minuti. Il server verifica finestra oraria, ammissione, componente e flag delle consultazioni. In un’unica transazione ricontrolla configurazione e sospensione, registra le sole schede ammesse e consuma i corrispondenti diritti. I flag impediscono un secondo deposito della stessa consultazione. Non viene salvato un riferimento permanente tra persona e preferenza nel nuovo archivio; il controllo tecnico riguarda il codice, mentre la consegna unica alla persona dipende dal seggio.',
 'Se la transazione fallisce non viene consumato il diritto senza la scheda. Se si perde solo la risposta, getVoterSessionStatus riconosce la sessione completata e restituisce quantità di schede e completamento, mai preferenze o ID di urna. Se l’invio è ancora pendente si può riprovare con la stessa sessione. Alla scadenza si usa lo stesso codice; i flag restano. Non assegnare automaticamente un codice nuovo per un errore di rete. Lo smarrimento definitivo del cedolino richiede una decisione del seggio: senza una mappa nominativa non è possibile individuarlo e sostituirlo automaticamente in sicurezza.'
 ]},
 {title:'4. Apertura, blocco e ripresa',paragraphs:[
 'Le cinque consultazioni hanno atti, date e ore distinti in Europe/Rome. L’inizio è incluso; l’orario di chiusura è escluso. I controlli sono eseguiti dal backend anche nella transazione di deposito: l’orologio del browser non decide l’ammissione. Durante l’intervallo tra consultazioni il sistema non permette il voto fuori dalle rispettive fasce.',
 'La modalità nominativa storica resta non ammessa al voto reale. Il nuovo processo richiede un rapporto di collaudo completo, proposta con documento e impronta, verifica di una persona diversa dall’autore e dal proponente e autorizzazione della Commissione. Il programma controlla account, nomi, release, configurazione e revisione delle credenziali; l’indipendenza effettiva e la veridicità delle prove richiedono gli atti della scuola.',
 'Uno stato verde significa che i requisiti automatici e le attestazioni previste risultano registrati. Non è una certificazione della legge o di assenza di vulnerabilità. Una sospensione invalida l’autorizzazione corrente. La ripresa richiede una nuova sequenza documentata, tutti i controlli preliminari e un evento separato di riapertura. Nessuna proroga degli orari è implicita. Dopo la chiusura del procedimento non si riapre con questo comando.',
 'Cambio di commit, configurazione o lotto invalida il precedente legame con le prove. Nelle finestre iniziate sono congelati calendario, liste e parametri protetti. I poteri amministrativi del cloud restano esterni all’applicazione: vanno limitati e verificati.'
 ]},
 {title:'5. Scrutinio e integrità dei risultati',paragraphs:[
 'Il deposito convalida componente, liste, candidati, numero di preferenze e duplicati. Una richiesta non valida è respinta senza scrivere una scheda. La scheda bianca ammessa è registrata come bianca. Una richiesta API respinta non è automaticamente una scheda nulla: le valutazioni elettorali competono alla Commissione.',
 'Dopo l’ultima chiusura della singola consultazione, gli account autorizzati ottengono conteggi aggregati. Le righe sintetiche sono costruite dai totali e non rappresentano schede individuali, ordini di deposito o reali combinazioni delle preferenze. Prima della chiusura i risultati parziali delle scelte non sono esposti. La distribuzione dei seggi, le convalide e gli ex aequo mantengono la logica esistente e la relativa verbalizzazione.',
 'AES-256-GCM protegge la confidenzialità a riposo e rileva alterazioni senza la chiave corretta. IV casuali, derivazione per anno/urna e dimensione fissa riducono alcune correlazioni. Il backend detiene la chiave e vede il voto prima della cifratura: non è cifratura end-to-end né scrutinio a custodi multipli. Un amministratore cloud con privilegi e chiavi potrebbe alterare dati e registri. Servono segregazione, doppio controllo, copie custodite e confronto indipendente dei totali.',
 'Il fascicolo ZIP contiene impronte SHA-256 verificabili dei file inclusi. Inventario, commit e impronta della configurazione identificano l’oggetto della revisione. Le impronte non sostituiscono firma, marca temporale, protocollo, backup o conservazione a norma. Non vengono dichiarati registri immutabili o prove crittografiche di correttezza universale del conteggio.'
 ]},
 {title:'6. Fornitori e infrastrutture',rows:[
 ['Servizio','Dati / funzione','Localizzazione e ruolo privacy'],
 ['Vercel','HTML, API; richieste HTTPS, credenziali di accesso, dati delle operazioni e metadati tecnici','Regione effettiva, log, supporto e trasferimenti da documentare. Negli errori forniti è indicata esecuzione iad1; non viene dichiarata una collocazione esclusivamente UE. Verificare contratto art. 28 e sub-responsabili.'],
 ['Google Firebase / Google Cloud','Firestore, Firebase Auth staff, API amministrative, SDK su gstatic','Regione database, repliche, Auth, assistenza e backup da verificare separatamente. La regione eur3 mostrata nello screenshot non localizza tutti i servizi. Ruoli e garanzie da acquisire contrattualmente.'],
 ['GitHub / GitHub Pages','Repository e distribuzione dei file pubblici; metadati di accesso e deploy','Non deve ospitare elenchi elettorali, codici, chiavi o fascicoli riservati. Localizzazione, condizioni e ruoli pertinenti da verificare.'],
 ['DNS e certificati dei domini dei provider','Risoluzione di elezione-levi.vercel.app e commissioneelettorale.github.io, TLS','Gestiti dai fornitori dei domini: verificare eventuali domini personalizzati e catena dei responsabili prima di aggiungerli.'],
 ['Librerie locali / npm in fase di build','PDF, ZIP, Excel, icone, stili, backend','Nessun servizio email applicativo o analytics individuato nel codice distribuito. Servizi aggiunti nelle console, log drains e integrazioni esterne devono essere censiti dalla scuola.']
 ]},
 {title:'7. Misure di sicurezza e limiti',paragraphs:[
 'HTTPS/TLS tramite i provider; API POST con origine ammessa, no-store, credenziali browser omesse e nessun ripiego automatico su vecchie Functions. Il voto non invia il token Firebase dello staff. L’autorizzazione effettiva è server-side; CORS non è un sistema di autenticazione.',
 'Password staff con scrypt e salt casuale, migrazione di credenziali precedenti al login valido, cambio iniziale obbligatorio dove previsto. Account revocati, anno e versione della sessione vengono ricontrollati. La chiave FIREBASE_SERVICE_ACCOUNT_JSON rimane nell’ambiente server. Non è inclusa nei fascicoli o nel browser. La rotazione richiede custodia delle chiavi per leggere le urne storiche.',
 'Un limite in memoria riduce i tentativi ripetuti di login sulla singola istanza (12 in 5 minuti); non è un limite distribuito. La scuola deve verificare WAF, IAM minimo, MFA degli amministratori cloud, separazione degli ambienti, console, Rules effettivamente distribuite, vulnerabilità e aggiornamenti. Le Rules vietano ai client le urne e le nuove credenziali; Admin SDK le supera e deve essere governato separatamente.',
 'Gli errori applicativi riportano operazione e codice, senza corpo della richiesta o scelte. I log del provider possono includere IP, timestamp e metadati; non sono acquisiti automaticamente da questo fascicolo. Non attivare body logging o registrazioni video. Il collaudo su dati fittizi non prova da solo le impostazioni delle console Production.'
 ]},
 {title:'8. Backup e ripristino',paragraphs:[
 'Non è implementato un job di backup attestato dal codice. Frequenza, durata, ubicazione, cifratura, custodi, RTO/RPO e prova di restore devono essere inseriti nella scheda riservata. Un download del fascicolo non è un backup delle urne. Non attribuire al piano Firebase Spark funzionalità di backup non verificate.',
 'Separare registro nominativo, credenziali, urne, chiavi e documenti. Le copie di versioni vecchie possono conservare abbinamenti nominativi e metadati: la cifratura successiva del database attivo non li cancella. Il ripristino va provato in un ambiente isolato senza riaprire automaticamente il voto, confrontando configurazione, conteggi e stato dei diritti. Mai ripristinare i flag di un istante e l’urna di un altro.',
 'Nel nuovo processo il backup non dovrebbe contenere mappe codice-nome perché non vengono create dall’app; esportazioni di stampa, cronologia, log di rete o registri compilati male possono reintrodurle. La verifica deve comprendere anche questi canali. Conservare le evidenze necessarie in caso di incidente, evitando copie superflue.'
 ]},
 {title:'9. Conservazione e cancellazione',rows:[
 ['Categoria','Criterio / attività richiesta'],
 ['Aventi diritto','Durata e massimario del procedimento; separazione dagli atti pubblici e gestione dei ricorsi. Termine da adottare.'],
 ['Account','Scadenza incarico e chiusura procedimento; revoca operativa distinta dalla cancellazione di evidenze amministrative.'],
 ['Credenziali / partecipazione','Solo quanto necessario all’unicità e alle contestazioni. I record scaduti non hanno una TTL generale automatica.'],
 ['Urna digitale e chiavi','Conservazione coordinata con scrutinio, verifiche e ricorsi; nessuna cancellazione per nascondere anomalie.'],
 ['Risultati e verbali','Piano di conservazione e pubblicazione scolastico; non un termine unico arbitrario per tutti i dati.'],
 ['Log tecnici / amministrativi','Tempi distinti per sicurezza e prova documentale; accesso limitato e tracciato; cloud e app censiti separatamente.'],
 ['Backup','Scadenza, ciclo di sovrascrittura, copie offline e gestione del legal hold da documentare.'],
 ['Esportazioni','Registro delle copie, responsabile della custodia e cancellazione sicura delle copie di lavoro, incluse stampe e download.']
 ]},
 {title:'10. Rischi da sottoporre a valutazione',rows:[
 ['Scenario','Misure implementate / rischio residuo'],
 ['Furto del codice / impersonificazione','Codice casuale non indovinabile e consegna controllata. La cessione volontaria o la copia del cedolino restano rischi; presidiare il seggio e custodire i lotti.'],
 ['Voto multiplo','Transazione atomica e flag per consultazione; numero dei codici limitato al registro. La consegna di più codici a una persona richiede controllo organizzativo.'],
 ['Accesso amministrativo','Ruoli, revoca, scadenza, cambio password; amministratori cloud e account condivisi richiedono valutazione separata.'],
 ['Correlazione identità-voto','Archivio non nominativo e urne separate; restano IP, tempi, piccoli gruppi, osservazione delle postazioni e collusione. Nessun anonimato assoluto attestato.'],
 ['Alterazione dell’urna','Cifratura autenticata e accesso API; il gestore con chiavi non è escluso crittograficamente. Confronto e custodia indipendenti necessari.'],
 ['Perdita dati / chiavi','Nessun piano provider attestato automaticamente: backup, restore e custodi devono essere verificati prima dell’uso.'],
 ['Indisponibilità / rete','Stato sessione e ricevuta senza preferenze, sospensione/ripresa; non è garantita l’assenza di downtime.'],
 ['Segretezza dei risultati piccoli','API aggregata; risultati di gruppi ridotti o unanimi possono rivelare informazioni. Valutare modalità di pubblicazione e accesso.'],
 ['Errori amministrativi / atti errati','Profili distinti, controlli e matrice; la correttezza dei protocolli e la base giuridica non sono decidibili dal programma.'],
 ['Dipendenze e fornitura del codice','Inventario e audit di sviluppo; una scansione senza segnalazioni non è un penetration test o garanzia su future vulnerabilità.']
 ]},
 {title:'11. Incidenti e data breach',paragraphs:[
 'Rilevazione tramite segnalazioni, errori, controlli e log pertinenti. Il tecnico informa tempestivamente Commissione e Dirigente; il Titolare coinvolge il DPO per gli aspetti privacy. Registrare fatti, impatto, misure, tempi, persone e riferimenti del fascicolo; non trascrivere voti o credenziali.',
 'Se occorre sospendere, il backend blocca nuovi depositi e conserva quelli già completati. Acquisire le evidenze minime, limitare l’accesso, evitare cancellazioni e preservare la catena di custodia. Il Titolare valuta obblighi di notifica al Garante entro 72 ore dalla conoscenza quando dovuta e comunicazione agli interessati nei casi previsti. Non tutti gli errori tecnici sono data breach; la decisione e le motivazioni vanno documentate.',
 'Intervento, prova di correzione, verifica indipendente e autorizzazione precedono la ripresa. La procedura applicativa non invia autonomamente notifiche al Garante o email e non prolunga le finestre elettorali.'
 ]},
 {title:'12. Informativa, cookie e browser',paragraphs:[
 'L’informativa effettivamente pubblicata è note-legali.html, inclusa nel pacchetto. Il sorgente non scrive cookie applicativi, non inizializza Analytics, non registra preferenze nel log di prova. Firebase Auth è inizializzato con inMemoryPersistence; Firestore non ha persistenza offline abilitata. La sessione di voto è tenuta in memoria. Il codice rimuove, quando il browser lo permette, residui della precedente persistenza di questa app.',
 'La verifica statica e i test della funzione di trasporto non equivalgono all’ispezione completa di cookie, storage e richieste su tutti i browser reali. Una prova in browser pulito, dopo login e logout, è richiesta nel collaudo; risultati e metadati provider devono essere allegati con dati fittizi. Nessun banner di consenso fittizio viene aggiunto per nascondere questa verifica.'
 ]},
 {title:'13. Collaudi, matrice e versione',paragraphs:[
 'Il pacchetto distingue le prove automatiche di sviluppo dalle prove operative dichiarate da persone. Ogni nuovo test registrato comprende requisito, metodo, atteso, osservato, esito, data e riferimento. Il rapporto conserva operatore, commit e configurazione. Rapporti storici senza questi dati restano identificati come incompleti; non vengono riscritti per farli apparire superati.',
 'La matrice associa controlli dell’Allegato A a annotazioni e prove. Le voci vuote rimangono NON VERIFICATO. Le prove di backup, accessibilità, infrastruttura e non correlazione richiedono evidenze effettive. Il commit del deploy, la configurazione e l’inventario sono inclusi: il parere deve richiamare questi identificativi, l’anno e le consultazioni, e va riesaminato dopo cambiamenti pertinenti.'
 ]},
 {title:'14. Fonti e campo di applicazione',paragraphs:[
 'Allegato A fornito dalla scuola, impronta SHA-256 30b1aadb76827d584a379826da9d5d8d854941732b03f17a76bcf713c19b2102. L’adozione e i campi di protocollo richiedono gli atti della scuola. L’O.M. 215/1991 e le disposizioni pertinenti a Consiglio, Consulta e rappresentanti di classe restano distinte. Non sono inventate date o circolari USR 2026.',
 'La Nota MIM 3803 del 30 giugno 2026 e l’Allegato tecnico sulle attività collegiali deliberative a distanza non sono assunti come autorizzazione generale alle elezioni telematiche. Il processo in presenza proposto deve essere valutato e adottato per la specifica consultazione. Se la valutazione conclude che i requisiti essenziali non sono soddisfatti, non confermare il superamento: utilizzare il procedimento alternativo ammesso dagli organi competenti.',
 'GDPR, artt. 5, 24, 25, 28, 32–39 e capo V: https://eur-lex.europa.eu/eli/reg/2016/679/oj?locale=it. Indicazioni DPIA: https://www.edpb.europa.eu/our-work-tools/our-documents/guidelines/data-protection-impact-assessments-high-risk-processing_en. Cookie: https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/9677876.'
 ]}
 ];
 function reviewSections(data){
  const review=data.review||{},profile=data.profile||{},logs=data.technical?.logs||[];
  return [{title:'Identificazione della copia riservata',paragraphs:[`Fascicolo ${VERSION}; anno ${review.year||'non indicato'}; generato ${data.generatedAt||'non indicato'}.`,`Release: ${review.release?.commit||'NON ATTESTATA'}; ambiente ${review.release?.environment||'NON ATTESTATO'}.`,`SHA-256 configurazione: ${review.configurationSha256||'NON ATTESTATA'}.`,`Stato procedura: ${review.review?.stage||'PREPARATION'}; ammissione registrata: ${review.assessment?.admittedToSecretVoting===true?'SÌ':'NO'}.`,`DPO: Vargiu Scuola S.r.l. - dpo@vargiuscuola.it. Copia riservata: custodire nel fascicolo della scuola.`]},...sections,
   {title:'15. Dati organizzativi dichiarati dalla scuola',paragraphs:Object.entries(fields).map(([key,label])=>label+': '+(profile.fields?.[key]||'NON DOCUMENTATO - da acquisire prima della valutazione.'))},
   {title:'16. Matrice delle attestazioni applicative',rows:[['Requisito','Stato','Evidenza dichiarata'],...(review.assessment?.controls||[]).map(c=>[c.id,c.status,c.note||'NON DOCUMENTATA'])]},
   {title:'17. Rapporti e checkpoint disponibili',paragraphs:[`Registrazioni incluse: ${logs.length}. Fotografia log fino a: ${data.technical?.snapshotUntil||'non attestata'}. I log dei fornitori sono separati. Nessun controllo mancante è trasformato in PASS.`]},
   ...logs.filter(l=>l.report).map(l=>({title:'Collaudo '+l.id,paragraphs:[`Operatore: ${l.technicianName}; registrato ${l.at}; versione ${l.release?.commit||l.report.softwareVersion||'NON ATTESTATA'}.`,`Configurazione: ${l.configurationSha256||'NON ATTESTATA'}; esito ${l.result}.`],rows:[['Prova','Metodo / atteso','Osservato / esito / evidenza'],...l.report.tests.map(t=>[t.id,`${t.method||'Non documentato'} / ${t.expected||'Non documentato'}`,`${t.observed||'Non documentato'}; ${t.outcome}; ${t.testedAt||'data non documentata'}; ${t.evidence||''}`])]}))];
 }
 return {VERSION,fields,sections,reviewSections};
});
